// <auto-generated />
namespace HwProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class studentidinprd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentidinprd));
        
        string IMigrationMetadata.Id
        {
            get { return "201806052157104_studentid-in-prd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
