//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HwProj.GitHubService.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HwProj.GitHubService.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @@ -16,6 +16,8 @@ Project(&quot;{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}&quot;) = &quot;F_Sharp_5&quot;, &quot;F_Sharp_5\F_Sh
        /// EndProject
        /// Project(&quot;{6EC3EE1D-3C4E-46DD-8F32-0CC8E7565705}&quot;) = &quot;F_Sharp_5.Test&quot;, &quot;F_Sharp_5.Test\F_Sharp_5.Test.fsproj&quot;, &quot;{013C4383-C99F-4844-9A0D-E2D539220E3F}&quot;
        /// EndProject
        ///+Project(&quot;{F2A71F9B-5D33-465A-A702-920D77279786}&quot;) = &quot;Phonebook(Task5)&quot;, &quot;Phonebook(Task5)\Phonebook(Task5).fsproj&quot;, &quot;{62077EB4-3019-4E90-910F-F306B5ABE9E7}&quot;
        ///+EndProject
        /// Global
        /// 	GlobalSection(SolutionConfigurationPlatforms) = pr [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DiffModule {
            get {
                return ResourceManager.GetString("DiffModule", resourceCulture);
            }
        }
    }
}
