//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HwProj.GitHubService.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HwProj.GitHubService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;XML&quot;: {
        ///    &quot;aliases&quot;: [
        ///      &quot;rss&quot;, 
        ///      &quot;xsd&quot;, 
        ///      &quot;wsdl&quot;
        ///    ], 
        ///    &quot;extensions&quot;: [
        ///      &quot;.xml&quot;, 
        ///      &quot;.adml&quot;, 
        ///      &quot;.admx&quot;, 
        ///      &quot;.ant&quot;, 
        ///      &quot;.axml&quot;, 
        ///      &quot;.builds&quot;, 
        ///      &quot;.ccproj&quot;, 
        ///      &quot;.ccxml&quot;, 
        ///      &quot;.clixml&quot;, 
        ///      &quot;.cproject&quot;, 
        ///      &quot;.cscfg&quot;, 
        ///      &quot;.csdef&quot;, 
        ///      &quot;.csl&quot;, 
        ///      &quot;.csproj&quot;, 
        ///      &quot;.ct&quot;, 
        ///      &quot;.depproj&quot;, 
        ///      &quot;.dita&quot;, 
        ///      &quot;.ditamap&quot;, 
        ///      &quot;.ditaval&quot;, 
        ///      &quot;.dll.config&quot;, 
        ///      &quot;.dotsettings&quot;, 
        ///      &quot;.filters&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string LinguistJson {
            get {
                return ResourceManager.GetString("LinguistJson", resourceCulture);
            }
        }
    }
}
